# Generated by Django 3.1.7 on 2021-04-29 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nike_run_app', '0002_auto_20210428_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men', models.CharField(max_length=3)),
                ('women', models.CharField(max_length=3)),
                ('kids', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='shoe_category',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='image_path',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='shoe_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='shoe',
            name='size2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='nike_run_app.size'),
        ),
    ]
