# Generated by Django 3.1.7 on 2021-04-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike_run_app', '0003_auto_20210428_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='kids',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='men',
            new_name='s1',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='women',
            new_name='s2',
        ),
        migrations.AddField(
            model_name='size',
            name='s3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='s4',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='s5',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
