# Generated by Django 3.1.7 on 2021-04-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike_run_app', '0004_auto_20210428_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
