# Generated by Django 3.1.7 on 2021-04-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nike_run_app', '0006_auto_20210428_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='size2',
        ),
    ]
