# Generated by Django 3.1.7 on 2021-04-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike_run_app', '0007_auto_20210429_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.IntegerField(),
        ),
    ]
