# Generated by Django 2.2 on 2021-04-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike_run_app', '0008_auto_20210429_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ss_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_date',
            field=models.DateTimeField(),
        ),
    ]
