# Generated by Django 3.1.7 on 2021-04-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike_run_app', '0009_auto_20210430_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='cat',
            field=models.CharField(max_length=10),
        ),
    ]
